### ISSUE TITLE
Rendering issue with car on iOS 15.4 where it doesn't update when camera is moving

### ISSUE THREAD

**Issue by yaustar** [playcanvas/model-viewer#165]
Sent this out to a potential client and they had this rendering issue with the lamborghini car test model where the rendering of the car doesn't update

https://user-images.githubusercontent.com/16639049/161168766-68bee93c-a7e5-447a-9bc9-ad3f0dcaca33.mp4

Device is iPhone 11 Pro on iOS 15.4

**Comment by yaustar** [comment]
I've been unable to reproduce this on browsertack with iOS 15.0 on the same device model

Unable to reproduce on iOS 15.3 too

Wondering if it's related to iOS 15.4?

**Comment by yaustar** [comment]
Confirmed that the issue happens on iOS 15.4.1 and doesn't happen on iOS 15.2

**Comment by yaustar** [comment]
Just tried a normal PlayCanvas app with auto render disabled on 15.4.1 and that works fine. The issue seems specific to the model viewer

**Comment by slimbuck** [comment]
It seems related to multisampling the offscreen render target. Disabling multiple samples results in it working correctly.

**Comment by mvaligursky** [comment]
So far from what I've seen the antialising on the framebuffer is causing the issue, but it's possible AA on render targets has some similar issue. I confirmed when testing the original issue that https://playcanvas.github.io/#/graphics/render-to-texture works correctly and uses 2 samples on the render target.

Feel free to set maxSamples to 1 to avoid it as you suggested https://github.com/playcanvas/engine/pull/4184#issuecomment-1092548670

**Comment by slimbuck** [comment]
> So far from what I've seen the antialising on the framebuffer is causing the issue, but it's possible AA on render targets has some similar issue. I confirmed when testing the original issue that https://playcanvas.github.io/#/graphics/render-to-texture works correctly and uses 2 samples on the render target.
> 
> Feel free to set maxSamples to 1 to avoid it as you suggested [playcanvas/engine#4184 (comment)](https://github.com/playcanvas/engine/pull/4184#issuecomment-1092548670)

One of the tickets you linked to mentioned offscreen buffers also being a problem. The RTT example with multisampling works for me too, but the viewer doesn't. Viewer creates a depth texture for reading later, perhaps that's the difference.

**Comment by yaustar** [comment]
Confirmed fixed  with the latest release of the model viewre
