### ISSUE TITLE
Just want to ask a few simple questions?

### ISSUE THREAD

**Issue by KaminariOS** [playcanvas/model-viewer#212]
I notice that this app can load a model less than 1s. I am quite curious how this is done.
I also built a glTF renderer [rustracer](https://github.com/KaminariOS/rustracer) but it take me seconds or even tens of seconds to load a model.

And where are the shaders? I cannot find it in the src folder.

**Comment by yaustar** [comment]
The model viewer uses https://github.com/playcanvas/engine as the renderer. You will find the GLB loader/parsing code, shaders etc there :)
