### ISSUE TITLE
Expose debug rendering functionality

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/model-viewer#213]
expose functionality from this engine PR
https://github.com/playcanvas/engine/pull/5261

![image](https://user-images.githubusercontent.com/59932779/233979668-36754206-b5c1-4c98-a3ce-66f11ac4704a.png)

**Comment by mvaligursky** [comment]
@jiajasper for UX design

**Comment by willeastcott** [comment]
Done in https://github.com/playcanvas/model-viewer/pull/216
