### ISSUE TITLE
Build: shader compile error when updating dependencies

### ISSUE THREAD

**Issue by epreston** [playcanvas/model-viewer#229]
Determining source of error when updating dependencies.  Fragment shader error below.

**Comment by epreston** [comment]
```
webgl-shader.js:165 Failed to compile fragment shader:

ERROR: 0:503: 'litShaderArgs' : undeclared identifier
ERROR: 0:503: 'opacity' :  field selection requires structure, vector, or interface block on left hand side
ERROR: 0:503: 'assign' : l-value required (can't modify a const)

498:	    fadeShadow(light0_shadowCascadeDistances);
499:	    float shadow0 = getShadowVSM16(SHADOWMAP_PASS(light0_shadowMap), dShadowCoord, light0_shadowParams, 5.54, dLightDirW);
500:	    dAtten *= mix(1.0, shadow0, light0_shadowIntensity);
501:	    dDiffuseLight += dAtten * light0_color;
502:	
503:	    litShaderArgs.opacity = mix(light0_shadowIntensity, 0.0, shadow0);
504:	    gl_FragColor.rgb = vec3(0.0);
505:	
506:	gl_FragColor.a = litArgs_opacity;
507:	
508:	}
```

**Comment by epreston** [comment]
Upgrading past "playcanvas": "1.64.4" is one thing that causes the issue.

**Comment by kungfooman** [comment]
New format is `litArgs_opacity` for example, you probably have custom chunks somewhere which require some updating.

**Comment by epreston** [comment]
@kungfooman you are a gentleman and a scholar. Thank you.

**Comment by epreston** [comment]
Source base and build is not compatible with lint rules past "@playcanvas/eslint-config": "1.5.0".  Adding the ".ts" extension to imports would require some structural changes.

**Comment by epreston** [comment]
type errors are masked by not setting "baseDir" in the tsconfig.json

**Comment by epreston** [comment]
Eslint config issue can be removed with the following in the `package.json` or by updating the rule in "@playcanvas/eslint-config"

```json
  "eslintConfig": {
    "rules": {
      "import/extensions": ["error", "always", { "ts": "never" }],
    }
  },
```

**Comment by epreston** [comment]
PR for ts extension warnings issue here.

https://github.com/playcanvas/playcanvas-eslint-config/pull/17

While not required for this package, it was requested.

**Comment by epreston** [comment]
A simple change to `litArgs_opacity` for the custom shader chunk in the shadow catcher fixes the original issue.  

Changes included in engine deps update linked above.
