### ISSUE TITLE
npm run serve and 404

### ISSUE THREAD

**Issue by joket1999** [playcanvas/model-viewer#238]
![图片](https://github.com/playcanvas/model-viewer/assets/6611880/aba3be26-5d56-45d7-b3af-ef88cb911c0e)

![图片](https://github.com/playcanvas/model-viewer/assets/6611880/b436e404-0075-447b-9c7c-1585b27cf8b7)

**Comment by willeastcott** [comment]
Can you confirm you did `npm run build` before you did `npm run serve`?

**Comment by willeastcott** [comment]
Closing since @joket1999 did not respond. However, please feel free to reopen if you still consider this to be a bug.
